version: '3.8'
services:
  golinky:
    image: ghcr.io/didactiklabs/golinky:latest
    container_name: golinky
    environment:
      - TZ=Europe/Paris
    volumes:
      - golinky-data:/app/data
    ports:
      - "8080:8080"
    restart: unless-stopped
volumes:
  golinky-data:
