apiVersion: apps/v1
kind: Deployment
metadata:
  name: golinky
  labels:
    app: golinky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golinky
  template:
    metadata:
      labels:
        app: golinky
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        # Optional Netbird sidecar container for secure remote access to the Golinky instance. Requires a PersistentVolumeClaim named "netbird" to store Netbird's state.
        # - name: netbird
        #   image: netbirdio/netbird:latest
        #   securityContext:
        #     privileged: true
        #   env:
        #     - name: NB_LOG_LEVEL
        #       value: "info"
        #     - name: NB_HOSTNAME
        #       value: "go"
        #   args: ["up"]
        #   volumeMounts:
        #     - name: netbird
        #       mountPath: /var/lib/netbird
        #   resources:
        #     requests:
        #       memory: "64Mi"
        #       cpu: "100m"
        #     limits:
        #       memory: "128Mi"
        #       cpu: "200m"
        - name: golinky
          image: ghcr.io/didactiklabs/golinky:latest
          args: ["-listen", "0.0.0.0:80", "-sqlitedb", "/app/data/golinky.db"]
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          env:
            - name: TZ
              value: "Europe/Paris"
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /app/data
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        # Optional Netbird volume for secure remote access to the Golinky instance.
        # - name: netbird
        #   persistentVolumeClaim:
        #     claimName: netbird
        - name: data
          persistentVolumeClaim:
            claimName: data
